static const BOOL chars[26][16] = {
	// A
	{
		FALSE, TRUE, TRUE, FALSE, 
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, FALSE, FALSE, TRUE, 
	}, 
	// B
	{
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, TRUE, TRUE, FALSE, 
	}, 
	// C
	{
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
	}, 
	// D
	{
		TRUE, TRUE, TRUE, FALSE, 
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, TRUE, TRUE, FALSE, 
	}, 
	// E
	{
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, FALSE, FALSE, FALSE, 
		TRUE, TRUE, TRUE, TRUE, 
	}, 
	// F
	{
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
	}, 
	// G
	{
		FALSE, TRUE, TRUE, TRUE, 
		TRUE, FALSE, FALSE, FALSE, 
		TRUE, FALSE, TRUE, TRUE, 
		FALSE, TRUE, TRUE, FALSE, 
	}, 
	// H
	{
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, FALSE, FALSE, TRUE, 
	}, 
	// I
	{
		FALSE, TRUE, TRUE, FALSE, 
		FALSE, TRUE, TRUE, FALSE, 
		FALSE, TRUE, TRUE, FALSE, 
		FALSE, TRUE, TRUE, FALSE, 
	}, 
	// J
	{
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
	}, 
	// K
	{
		TRUE, FALSE, TRUE, TRUE, 
		TRUE, TRUE, FALSE, FALSE, 
		TRUE, TRUE, TRUE, FALSE, 
		TRUE, FALSE, FALSE, TRUE, 
	}, 
	// L
	{
		TRUE, FALSE, FALSE, FALSE, 
		TRUE, FALSE, FALSE, FALSE, 
		TRUE, FALSE, FALSE, FALSE, 
		TRUE, TRUE, TRUE, TRUE, 
	}, 
	// M
	{
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
	}, 
	// N
	{
		TRUE, TRUE, FALSE, TRUE, 
		TRUE, TRUE, FALSE, TRUE, 
		TRUE, FALSE, TRUE, TRUE, 
		TRUE, FALSE, TRUE, TRUE, 
	}, 
	// O
	{
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
	}, 
	// P
	{
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, FALSE, FALSE, FALSE, 
	}, 
	// Q
	{
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
	}, 
	// R
	{
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, FALSE, TRUE, FALSE, 
		TRUE, FALSE, FALSE, TRUE, 
	}, 
	// S
	{
		TRUE, TRUE, TRUE, TRUE, 
		TRUE, TRUE, FALSE, FALSE, 
		FALSE, FALSE, TRUE, TRUE, 
		TRUE, TRUE, TRUE, TRUE
	}, 
	// T
	{
		TRUE, TRUE, TRUE, TRUE,
		FALSE, TRUE, TRUE, FALSE, 
		FALSE, TRUE, TRUE, FALSE, 
		FALSE, TRUE, TRUE, FALSE, 
	}, 
	// U
	{
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, TRUE, TRUE, TRUE, 
	}, 
	// V
	{
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, FALSE, TRUE, FALSE, 
		FALSE, TRUE, TRUE, FALSE, 
	}, 
	// W
	{
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, FALSE, FALSE, TRUE, 
		TRUE, FALSE, TRUE, TRUE, 
		TRUE, TRUE, TRUE, TRUE, 
	}, 
	// X
	{
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
	}, 
	// Y
	{
		TRUE, FALSE, FALSE, TRUE, 
		FALSE, TRUE, TRUE, FALSE, 
		FALSE, FALSE, TRUE, FALSE, 
		FALSE, TRUE, FALSE, FALSE, 
	}, 
	// Z
	{
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
		FALSE, FALSE, FALSE, FALSE, 
	}, 
};
